# Generated by Django 3.1.13 on 2021-12-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_tables', '0001_initial'),
        ('undp_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('output_id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('activity_status', models.IntegerField(blank=True, null=True)),
                ('activity_scope', models.IntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_website', models.CharField(blank=True, max_length=225, null=True)),
                ('policy_marker_vocabulary', models.IntegerField(blank=True, null=True)),
                ('policy_marker_code', models.IntegerField(blank=True, null=True)),
                ('policy_marker_significance', models.IntegerField(blank=True, null=True)),
                ('collaboration_type', models.IntegerField(blank=True, null=True)),
                ('default_flow_type', models.IntegerField(blank=True, null=True)),
                ('default_finance_type', models.IntegerField(blank=True, null=True)),
                ('default_aid_type', models.CharField(blank=True, max_length=5, null=True)),
                ('default_tied_status', models.IntegerField(blank=True, null=True)),
                ('capital_spend', models.FloatField(blank=True, null=True)),
                ('conditions_attached', models.IntegerField(blank=True, null=True)),
                ('crs_code', models.CharField(blank=True, max_length=15, null=True)),
                ('operating_unit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient_country', to='master_tables.operatingunit')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reporting_org', to='master_tables.organisation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
                ('signature_solution', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.signaturesolution')),
            ],
        ),
        migrations.CreateModel(
            name='OutputResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.IntegerField()),
                ('aggregation_status', models.IntegerField()),
                ('indicator_title', models.CharField(max_length=225)),
                ('indicator_description', models.TextField(blank=True, null=True)),
                ('indicator_measure', models.IntegerField()),
                ('indicator_ascending', models.IntegerField()),
                ('baseline_year', models.CharField(max_length=4)),
                ('baseline_comment', models.TextField(blank=True, null=True)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_outputs.output')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='SDGChartColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdg_code', models.IntegerField()),
                ('count', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Hows'), (2, 'Humanitarian'), (3, 'South-South and Triangular Cooperation'), (4, 'Joint Programme'), (5, 'Partner'), (6, 'Whos')], db_index=True)),
                ('parent_type', models.IntegerField(choices=[(0, 'default'), (1, 'Geographic'), (2, 'Shocks and Fragility'), (3, 'Socio-Economic'), (4, 'Status'), (5, 'UN Agency'), (6, 'International Financial Institution (IFI)')], db_index=True)),
                ('parent_marker_desc', models.CharField(blank=True, max_length=750, null=True)),
                ('marker_id', models.IntegerField()),
                ('marker_title', models.CharField(max_length=500)),
                ('marker_desc', models.CharField(blank=True, max_length=750, null=True)),
                ('level_two_marker_id', models.IntegerField()),
                ('level_two_marker_title', models.CharField(max_length=500)),
                ('level_two_marker_description', models.CharField(max_length=500)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='marker_output', to='undp_outputs.output')),
            ],
        ),
        migrations.CreateModel(
            name='OutputTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=10)),
                ('transaction_date', models.DateField()),
                ('amount', models.FloatField(blank=True, db_index=True, null=True)),
                ('amount_date', models.DateField(blank=True, null=True)),
                ('disbursement_channel', models.CharField(blank=True, max_length=5, null=True)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_outputs.output')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provider_org', to='master_tables.organisation')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_org', to='master_tables.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='OutputTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=8, max_digits=11)),
                ('year', models.IntegerField()),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_outputs.output')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.sdgtargets')),
            ],
        ),
        migrations.CreateModel(
            name='OutputSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_outputs.output')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.sector')),
            ],
        ),
        migrations.CreateModel(
            name='OutputSdg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_outputs.output')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
                ('sdg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.sdg')),
            ],
        ),
        migrations.CreateModel(
            name='OutputResultPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('target', models.TextField(blank=True, null=True)),
                ('actual', models.TextField(blank=True, null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_outputs.outputresult')),
            ],
        ),
        migrations.CreateModel(
            name='OutputParticipatingOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_id', models.CharField(blank=True, max_length=20, null=True)),
                ('organisation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('organisation_role', models.IntegerField(blank=True, null=True)),
                ('organisation_type', models.IntegerField(blank=True, null=True)),
                ('org_name', models.TextField(blank=True, null=True)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_outputs.output')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='OutputLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_reach', models.IntegerField()),
                ('location_vocabulary', models.CharField(max_length=4)),
                ('location_code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('activity_description', models.TextField(blank=True, null=True)),
                ('administrative_level', models.IntegerField()),
                ('administrative_code', models.IntegerField()),
                ('administrative_vocabulary', models.CharField(max_length=15)),
                ('srs_name', models.CharField(max_length=600)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('exactness', models.IntegerField()),
                ('location_class', models.IntegerField()),
                ('feature_designation', models.CharField(max_length=10)),
                ('operating_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.operatingunit')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_outputs.output')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='OutputActiveYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='output_active', to='undp_outputs.output')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=10)),
                ('transaction_date', models.DateField()),
                ('amount', models.FloatField(blank=True, db_index=True, null=True)),
                ('amount_date', models.DateField(blank=True, null=True)),
                ('disbursement_channel', models.CharField(blank=True, max_length=5, null=True)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_outputs.output')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='expense_provider_org', to='master_tables.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='CountryBudgetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('percentage', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('country_budget', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_outputs.countrybudget')),
            ],
        ),
        migrations.AddField(
            model_name='countrybudget',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_outputs.output'),
        ),
        migrations.AddField(
            model_name='countrybudget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project'),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, db_index=True, null=True)),
                ('amount_date', models.DateField(db_index=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('budget_type', models.IntegerField()),
                ('status', models.IntegerField()),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_outputs.output')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_date', models.DateField(db_index=True)),
                ('activity_type', models.IntegerField()),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_outputs.output')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
            ],
        ),
    ]
