# Generated by Django 4.1.5 on 2023-03-09 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iati_referentiel", "0002_location_boundary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iati_identifier",
                    models.BigIntegerField(db_column="Iati-identifier"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Intitulé")),
                (
                    "lang",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Language"
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        blank=True,
                        db_column="Default-currency",
                        max_length=255,
                        null=True,
                        verbose_name="Dévise",
                    ),
                ),
                (
                    "humanitarian",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Humanitaire"
                    ),
                ),
                (
                    "hierarchy",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Hiérachie"
                    ),
                ),
                (
                    "budget_not_provided",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Commercial Restrictions", "Commercial Restrictions"),
                            ("Legal Restrictions", "Legal Restrictions"),
                            ("Rapid Onset Emergency", "Rapid Onset Emergency"),
                        ],
                        db_column="Budget-not-provided",
                        max_length=255,
                        null=True,
                        verbose_name="Budget non approvisé",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "activity_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Identification", "Identification"),
                            ("Implementation", "Implementation"),
                            ("Finalisation", "Finalisation"),
                            ("Closed", "Closed"),
                            ("Cancelled", "Cancelled"),
                            ("Suspended", "Suspended"),
                        ],
                        db_column="Activity-status",
                        max_length=255,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "activity_scope",
                    models.CharField(
                        blank=True,
                        db_column="Activity-scope",
                        max_length=255,
                        null=True,
                        verbose_name="Portée Activité",
                    ),
                ),
                (
                    "type_relationship",
                    models.CharField(
                        blank=True,
                        db_column="Type-relationship",
                        max_length=255,
                        null=True,
                        verbose_name="Type Relation",
                    ),
                ),
                (
                    "planned_start",
                    models.DateField(
                        db_column="Planned-start", verbose_name="Début Planifié"
                    ),
                ),
                (
                    "planned_end",
                    models.DateField(
                        db_column="Planned-end", verbose_name="Fin Planifiée"
                    ),
                ),
                (
                    "actual_start",
                    models.DateField(
                        blank=True,
                        db_column="Actual-start",
                        null=True,
                        verbose_name="Début Réel",
                    ),
                ),
                (
                    "actual_end",
                    models.DateField(
                        blank=True,
                        db_column="Actual-end",
                        null=True,
                        verbose_name="Fin Réel",
                    ),
                ),
                (
                    "last_updated_datetime",
                    models.DateField(
                        auto_now=True, db_column="Last-updated-datetime", null=True
                    ),
                ),
                (
                    "activityid",
                    models.ForeignKey(
                        blank=True,
                        db_column="activityid",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.activity",
                        verbose_name="Projet Parent",
                    ),
                ),
                (
                    "collaboration_typeid",
                    models.ForeignKey(
                        blank=True,
                        db_column="Collaboration-typeID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_referentiel.collaborationtype",
                        verbose_name="Type Collaboration",
                    ),
                ),
                (
                    "conditionid",
                    models.ManyToManyField(
                        related_name="as_condition_activity",
                        to="iati_referentiel.condition",
                        verbose_name="Condition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activitée",
                "verbose_name_plural": "Activitées",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, db_column="Date", null=True, verbose_name="Date"
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Texte"
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire",
            },
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("format", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("lang", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "activityid",
                    models.ForeignKey(
                        db_column="activityid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien Document",
                "verbose_name_plural": "Lien Document",
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Unit", "Unit"),
                            ("Percentage", "Percentage"),
                            ("Nominal", "Nominal"),
                            ("Ordinal", "Ordinal"),
                            ("Qualitative", "Qualitative"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Mesure",
                    ),
                ),
                ("ascending", models.BooleanField(verbose_name="Ascendant")),
                (
                    "aggregation_status",
                    models.BooleanField(
                        db_column="Aggregation-status", verbose_name="Statut Agrégation"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Titre"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Code"
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicateur",
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        db_column="Period-start",
                        null=True,
                        verbose_name="Début Période",
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True,
                        db_column="Period-end",
                        null=True,
                        verbose_name="Fin période",
                    ),
                ),
                (
                    "indicatorid",
                    models.ForeignKey(
                        db_column="indicatorid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.indicator",
                        verbose_name="Indicateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Periode",
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Valeur"
                    ),
                ),
                (
                    "dimensionid",
                    models.ForeignKey(
                        db_column="dimensionid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.dimension",
                        verbose_name="Dimension",
                    ),
                ),
                (
                    "locationid",
                    models.ForeignKey(
                        db_column="locationid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_referentiel.location",
                        verbose_name="Localité",
                    ),
                ),
                (
                    "periodid",
                    models.ForeignKey(
                        db_column="periodid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.period",
                        verbose_name="Periode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jalon",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iati_identifier",
                    models.BigIntegerField(
                        db_column="Iati-identifier", editable=False, unique=True
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Réference"
                    ),
                ),
                ("humanitarian", models.BooleanField(verbose_name="Humanitaire")),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Incoming Funds", "Incoming Funds"),
                            ("Outgoing Commitment", "Outgoing Commitment"),
                            ("Disbursement", "Disbursement"),
                            ("Expenditure", "Expenditure"),
                            ("Interest Payment", "Interest Payment"),
                            ("Loan Repayment", "Loan Repayment"),
                            ("Reimbursement", "Reimbursement"),
                            ("Purchase of Equity", "Purchase of Equity"),
                            ("Sale of Equity", "Sale of Equity"),
                            ("Credit Guarantee", "Credit Guarantee"),
                            ("Incoming Commitment", "Incoming Commitment"),
                            ("Outgoing Pledge", "Outgoing Pledge"),
                            ("Incoming Pledge", "Incoming Pledge"),
                        ],
                        db_column="Transaction-type",
                        max_length=255,
                        null=True,
                        verbose_name="Type Transaction",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(
                        db_column="Transaction-date", verbose_name="Date Transaction"
                    ),
                ),
                ("value", models.FloatField(verbose_name="Montant")),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Dévise"
                    ),
                ),
                (
                    "value_date",
                    models.DateField(
                        db_column="Value-date", verbose_name="Date Montant"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "disbursement_channel",
                    models.CharField(
                        blank=True,
                        db_column="Disbursement-channel",
                        max_length=255,
                        null=True,
                        verbose_name="Chaîne de distribution",
                    ),
                ),
                (
                    "activityid",
                    models.OneToOneField(
                        blank=True,
                        db_column="activityid",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="activite_transaction",
                        to="iati_activities.activity",
                    ),
                ),
                (
                    "countryid3",
                    models.ForeignKey(
                        db_column="countryid3",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_referentiel.country",
                        verbose_name="Pays",
                    ),
                ),
                (
                    "organizationid",
                    models.ForeignKey(
                        db_column="organizationid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="receiver",
                        to="iati_referentiel.organization",
                        verbose_name="Receveur",
                    ),
                ),
                (
                    "organizationid2",
                    models.ForeignKey(
                        db_column="organizationid2",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="provider",
                        to="iati_referentiel.organization",
                        verbose_name="Donneur",
                    ),
                ),
                (
                    "regionid3",
                    models.ForeignKey(
                        db_column="regionid3",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_referentiel.region",
                        verbose_name="Région",
                    ),
                ),
                (
                    "sectorid",
                    models.ForeignKey(
                        db_column="sectorid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="secteur",
                        to="iati_referentiel.sector",
                        verbose_name="Secteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.CreateModel(
            name="Results",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Output", "Output"),
                            ("Outcome", "Outcome"),
                            ("Impact", "Impact"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "aggregation_status",
                    models.BooleanField(
                        db_column="Aggregation-status",
                        verbose_name="Status Aggregation",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Titre"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "activityid",
                    models.ForeignKey(
                        db_column="activityid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultat",
                "verbose_name_plural": "Resultats",
            },
        ),
        migrations.CreateModel(
            name="PlannedDisbursement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Type"
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        db_column="Period-start",
                        null=True,
                        verbose_name="Période Debut",
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True,
                        db_column="Period-end",
                        null=True,
                        verbose_name="Période Fin",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Montant")),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Dévide"
                    ),
                ),
                (
                    "value_date",
                    models.DateField(
                        blank=True,
                        db_column="Value-date",
                        null=True,
                        verbose_name="Valeur Date",
                    ),
                ),
                (
                    "activityid",
                    models.ForeignKey(
                        db_column="activityid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.activity",
                        verbose_name="Activité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Décaissement Prévu",
                "verbose_name_plural": "Décaissement Prévus",
            },
        ),
        migrations.AddField(
            model_name="indicator",
            name="resultsid",
            field=models.ForeignKey(
                db_column="resultsid",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="iati_activities.results",
                verbose_name="Resultat",
            ),
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_name",
                    models.CharField(
                        blank=True,
                        db_column="Person-name",
                        max_length=255,
                        null=True,
                        verbose_name="Nom et Prenom(s)",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, db_column="Job-title", max_length=255, null=True
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "website",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Site Web"
                    ),
                ),
                (
                    "organizationid",
                    models.ForeignKey(
                        db_column="organizationid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_referentiel.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iati_identifier",
                    models.BigIntegerField(
                        db_column="Iati-identifier", editable=False, unique=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("Original", "Original"), ("Revised", "Revised")],
                        max_length=255,
                        null=True,
                        verbose_name="Type Budget",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Indicative", "Indicative"),
                            ("Committed", "Committed"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Statut Budget",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        db_column="Period-start",
                        max_length=255,
                        null=True,
                        verbose_name="Période Début",
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True,
                        db_column="Period-end",
                        max_length=255,
                        null=True,
                        verbose_name="Période Fin",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Montant")),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Dévise"
                    ),
                ),
                (
                    "value_date",
                    models.DateField(
                        blank=True,
                        db_column="Value-date",
                        null=True,
                        verbose_name="Valeur Date",
                    ),
                ),
                (
                    "activityid",
                    models.OneToOneField(
                        blank=True,
                        db_column="activityid",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="activite_budget",
                        to="iati_activities.activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
            },
        ),
        migrations.CreateModel(
            name="Baseline",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Année")),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Valeur"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, db_column="Date", null=True, verbose_name="Date"
                    ),
                ),
                (
                    "indicatorid",
                    models.ForeignKey(
                        db_column="indicatorid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.indicator",
                        verbose_name="Indicateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de Base",
            },
        ),
        migrations.CreateModel(
            name="Actual",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Valeur"
                    ),
                ),
                (
                    "periodid",
                    models.ForeignKey(
                        db_column="periodid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.period",
                        verbose_name="Periode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultat Obtenu",
            },
        ),
        migrations.CreateModel(
            name="ActivityParticipatingOrg",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Funding", "Funding"),
                            ("Accountable", "Accountable"),
                            ("Extending", "Extending"),
                            ("Implementing", "Implementing"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "activityid",
                    models.ForeignKey(
                        db_column="activityid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.activity",
                        verbose_name="Projet",
                    ),
                ),
                (
                    "organizationid",
                    models.ForeignKey(
                        db_column="organizationid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_referentiel.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisme Participant",
                "verbose_name_plural": "Organismes Participants",
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="contact_infoid",
            field=models.ForeignKey(
                blank=True,
                db_column="Contact-infoID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="iati_activities.contactinfo",
                verbose_name="Contact",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="countryid3",
            field=models.ForeignKey(
                db_column="countryid3",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="iati_referentiel.country",
                verbose_name="Pays",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="default_aid_typeid",
            field=models.ForeignKey(
                blank=True,
                db_column="default-aid-typeID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="iati_referentiel.defaultaidtype",
                verbose_name="Type Aide Par Defaut",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="humanitarian_scopeid",
            field=models.ForeignKey(
                blank=True,
                db_column="Humanitarian-scopeID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="iati_referentiel.humanitarianscope",
                verbose_name="Portée Humanitaire",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="locationid",
            field=models.ForeignKey(
                db_column="locationid",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="iati_referentiel.location",
                verbose_name="Localisation",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="organizationid",
            field=models.ForeignKey(
                db_column="organizationid",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="bailleuractivite",
                to="iati_referentiel.organization",
                verbose_name="Bailleur",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="regionid3",
            field=models.ForeignKey(
                db_column="regionid3",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="iati_referentiel.region",
                verbose_name="Région",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="sectorid",
            field=models.ForeignKey(
                db_column="sectorid",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="iati_referentiel.sector",
                verbose_name="Secteur",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="tagid",
            field=models.ForeignKey(
                blank=True,
                db_column="tagid",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="iati_referentiel.tag",
                verbose_name="Etiquette",
            ),
        ),
        migrations.CreateModel(
            name="DefaultFinanceTypeActivity",
            fields=[
                (
                    "default_finance_typeid",
                    models.OneToOneField(
                        db_column="Default-finance-typeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="iati_referentiel.defaultfinancetype",
                        verbose_name="Type Financement",
                    ),
                ),
                (
                    "activityid",
                    models.ForeignKey(
                        db_column="activityid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de finance par défaut",
                "verbose_name_plural": "Type de finance par défaut",
                "unique_together": {("default_finance_typeid", "activityid")},
            },
        ),
        migrations.CreateModel(
            name="DefaultAidTypeActivity",
            fields=[
                (
                    "default_aid_typeid",
                    models.OneToOneField(
                        db_column="default-aid-typeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="iati_referentiel.defaultaidtype",
                        verbose_name="Type Aide Par Defaut",
                    ),
                ),
                (
                    "activityid",
                    models.ForeignKey(
                        db_column="activityid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.activity",
                        verbose_name="Activité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type Aide Par Defaut",
                "verbose_name_plural": "Type Aide Par Defaut",
                "unique_together": {("default_aid_typeid", "activityid")},
            },
        ),
        migrations.CreateModel(
            name="TargetComment2",
            fields=[
                (
                    "targetid",
                    models.OneToOneField(
                        db_column="targetid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="iati_activities.target",
                    ),
                ),
                (
                    "commentid",
                    models.ForeignKey(
                        db_column="commentid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.comment",
                        verbose_name="Commentaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire Jalon",
                "unique_together": {("targetid", "commentid")},
            },
        ),
        migrations.CreateModel(
            name="DocumentLinkResults",
            fields=[
                (
                    "document_linkid",
                    models.OneToOneField(
                        db_column="Document-linkID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="iati_activities.documentlink",
                        verbose_name="Lien Document",
                    ),
                ),
                (
                    "resultsid",
                    models.ForeignKey(
                        db_column="resultsid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.results",
                        verbose_name="Resultat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Résultat",
                "verbose_name_plural": "Document Résultat",
                "unique_together": {("document_linkid", "resultsid")},
            },
        ),
        migrations.CreateModel(
            name="DocumentLinkIndicator",
            fields=[
                (
                    "document_linkid",
                    models.OneToOneField(
                        db_column="Document-linkID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="iati_activities.documentlink",
                        verbose_name="Lien document",
                    ),
                ),
                (
                    "indicatorid",
                    models.ForeignKey(
                        db_column="indicatorid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.indicator",
                        verbose_name="Indicateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Indicateur",
                "verbose_name_plural": "Document Indicateur",
                "unique_together": {("document_linkid", "indicatorid")},
            },
        ),
        migrations.CreateModel(
            name="BaselineDocumentLink",
            fields=[
                (
                    "baselineid",
                    models.OneToOneField(
                        db_column="baselineid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="iati_activities.baseline",
                    ),
                ),
                (
                    "document_linkid",
                    models.ForeignKey(
                        db_column="Document-linkID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.documentlink",
                    ),
                ),
            ],
            options={
                "unique_together": {("baselineid", "document_linkid")},
            },
        ),
        migrations.CreateModel(
            name="ActualDocumentLink",
            fields=[
                (
                    "actualid",
                    models.OneToOneField(
                        db_column="actualid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="iati_activities.actual",
                    ),
                ),
                (
                    "document_linkid",
                    models.ForeignKey(
                        db_column="Document-linkID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.documentlink",
                        verbose_name="Lien Document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Réel",
                "verbose_name_plural": "Documents Réel",
                "unique_together": {("actualid", "document_linkid")},
            },
        ),
        migrations.CreateModel(
            name="ActualDimension",
            fields=[
                (
                    "actualid",
                    models.OneToOneField(
                        db_column="actualid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="iati_activities.actual",
                    ),
                ),
                (
                    "dimensionid",
                    models.ForeignKey(
                        db_column="dimensionid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_activities.dimension",
                        verbose_name="Dimension",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dimension Réel",
                "unique_together": {("actualid", "dimensionid")},
            },
        ),
    ]
