# Generated by Django 4.1.5 on 2023-01-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iati_activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="budget_not_provided",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Commercial Restrictions", "Commercial Restrictions"),
                    ("Legal Restrictions", "Legal Restrictions"),
                    ("Rapid Onset Emergency", "Rapid Onset Emergency"),
                ],
                db_column="Budget-not-provided",
                max_length=255,
                null=True,
                verbose_name="Budget non approvisé",
            ),
        ),
        migrations.AlterField(
            model_name="activitydate",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Planned start", "Planned start"),
                    ("Actual start", "Actual start"),
                    ("Planned End", "Planned End"),
                    ("Actual end", "Actual end"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="statusst",
            field=models.CharField(
                blank=True,
                choices=[("Indicative", "Indicative"), ("Committed", "Committed")],
                max_length=255,
                null=True,
                verbose_name="Statut Budget",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("Original", "Original"), ("Revised", "Revised")],
                max_length=255,
                null=True,
                verbose_name="Type Budget",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="measure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Unit", "Unit"),
                    ("Percentage", "Percentage"),
                    ("Nominal", "Nominal"),
                    ("Ordinal", "Ordinal"),
                    ("Qualitative", "Qualitative"),
                ],
                max_length=255,
                null=True,
                verbose_name="Mesure",
            ),
        ),
    ]
