# Generated by Django 4.1.5 on 2023-03-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iati_activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="iati_identifier",
            field=models.BigIntegerField(
                blank=True, db_column="Iati-identifier", editable=False, null=True
            ),
        ),
    ]
