# Generated by Django 4.1.5 on 2023-04-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iati_referentiel", "0002_location_boundary"),
        ("iati_activities", "0002_alter_budget_iati_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="iati_identifier",
            field=models.CharField(
                blank=True,
                db_column="Iati-identifier",
                max_length=255,
                null=True,
                verbose_name="Identifiant Iati",
            ),
        ),
        migrations.RemoveField(
            model_name="activity",
            name="locationid",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="sectorid",
        ),
        migrations.AddField(
            model_name="activity",
            name="locationid",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="as_location_activity",
                to="iati_referentiel.location",
                verbose_name="Localisation",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="sectorid",
            field=models.ManyToManyField(
                related_name="as_sector_activity",
                to="iati_referentiel.sector",
                verbose_name="Secteur",
            ),
        ),
    ]
