# Generated by Django 4.1.5 on 2023-06-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iati_activities", "0003_alter_activity_iati_identifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="planned_end",
            field=models.DateField(
                blank=True,
                db_column="Planned-end",
                null=True,
                verbose_name="Fin Planifiée",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="planned_start",
            field=models.DateField(
                blank=True,
                db_column="Planned-start",
                null=True,
                verbose_name="Début Planifié",
            ),
        ),
        migrations.AlterField(
            model_name="documentlink",
            name="format",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="documentlink",
            name="url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
