# Generated by Django 3.1.13 on 2021-12-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bureau', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('category', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MapBoundary',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('geometry', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='OperatingUnit',
            fields=[
                ('unit_type', models.CharField(blank=True, max_length=3, null=True)),
                ('iso_num', models.CharField(blank=True, max_length=5, null=True)),
                ('bureau_local', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('iso3', models.CharField(db_index=True, max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('language', models.CharField(blank=True, max_length=6, null=True)),
                ('iso2', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('web', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('area_type', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_recipient', models.BooleanField(default=False)),
                ('is_donor', models.BooleanField(default=False)),
                ('bureau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.bureau')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sdg',
            fields=[
                ('code', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('code', models.CharField(db_index=True, max_length=2, primary_key=True, serialize=False)),
                ('sector', models.CharField(blank=True, db_index=True, default=None, max_length=150, null=True)),
                ('color', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SignatureSolution',
            fields=[
                ('sp_output', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sp_output_description', models.TextField(max_length=1024)),
                ('ss_id', models.CharField(max_length=10)),
                ('sp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.sector')),
            ],
        ),
        migrations.CreateModel(
            name='SdgTargets',
            fields=[
                ('target_id', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(db_index=True, max_length=1000)),
                ('sdg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.sdg')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('region_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.bureau')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('ref_id', models.CharField(db_index=True, max_length=25, primary_key=True, serialize=False)),
                ('org_name', models.CharField(db_index=True, max_length=255)),
                ('short_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('type_level_1', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('type_level_2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('type_level_3', models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True)),
                ('level_3_name', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('operating_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.operatingunit')),
            ],
        ),
        migrations.AddField(
            model_name='operatingunit',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.region'),
        ),
    ]
