# Generated by Django 3.1.13 on 2022-02-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_tables', '0002_auto_20220121_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
    ]
