# Generated by Django 3.1.13 on 2021-09-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.IntegerField(choices=[(1, 'About Open.UNDP'), (2, 'FAQ'), (3, 'Glossary'), (4, 'Contact')], db_index=True, default=1, verbose_name='Tab')),
                ('plain_text', models.TextField(blank=True, null=True)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.IntegerField(choices=[(0, 'N/A'), (1, 'Upload Master Data'), (2, 'Download from Source Location'), (3, 'Annual XML Parsing'), (4, 'Parse Donors Data'), (5, 'Project Search model update'), (6, 'Purchase Orders Upload'), (7, 'Country documents Upload'), (8, 'Upload Map Boundaries'), (9, 'Populate project year summary'), (10, 'XML difference analysis'), (11, 'Initiate Automation')], db_index=True, default=0, verbose_name='Job')),
                ('status', models.IntegerField(choices=[(1, 'In Progress'), (2, 'Successful'), (3, 'Failed')], db_index=True, default=1, verbose_name='Download Status')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
