# Generated by Django 3.1.13 on 2021-12-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('undp_outputs', '0001_initial'),
        ('master_tables', '0001_initial'),
        ('undp_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorFundSplitUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_category', models.IntegerField(blank=True, choices=[(1, 'Pooled Funding'), (2, 'Private Sector'), (3, 'Vertical Funding'), (4, 'Other Multilaterals'), (5, 'NGOs'), (6, 'DAC Donors'), (7, 'Programme Countries'), (8, 'Others Unidentified'), (9, 'Financing Institutions'), (10, 'UN Agencies'), (11, 'European Union'), (12, 'Non-DAC and non-programme country'), (13, 'Non-DAC Donors'), (14, 'Foundations'), (15, 'UNDP Regular Resources'), (16, 'Non-DAC and programme governments'), (17, 'Private Sector/Foundations/NGOs')], db_index=True, default=8, null=True, verbose_name='Donor Category')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=30)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=30)),
                ('year', models.IntegerField(db_index=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.organisation')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_outputs.output')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='DonorFundModality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_category', models.IntegerField(blank=True, choices=[(1, 'Pooled Funding'), (2, 'Private Sector'), (3, 'Vertical Funding'), (4, 'Other Multilaterals'), (5, 'NGOs'), (6, 'DAC Donors'), (7, 'Programme Countries'), (8, 'Others Unidentified'), (9, 'Financing Institutions'), (10, 'UN Agencies'), (11, 'European Union'), (12, 'Non-DAC and non-programme country'), (13, 'Non-DAC Donors'), (14, 'Foundations'), (15, 'UNDP Regular Resources'), (16, 'Non-DAC and programme governments'), (17, 'Private Sector/Foundations/NGOs')], db_index=True, default=8, null=True, verbose_name='Donor Category')),
                ('fund_type', models.CharField(max_length=30)),
                ('fund_stream', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('contribution', models.DecimalField(decimal_places=2, max_digits=30)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.organisation')),
            ],
        ),
    ]
