# Generated by Django 3.1.13 on 2021-09-20 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('undp_outputs', '0001_initial'),
        ('master_tables', '0001_initial'),
        ('undp_donors', '0001_initial'),
        ('undp_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorfundsplitup',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_outputs.output'),
        ),
        migrations.AddField(
            model_name='donorfundsplitup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project'),
        ),
        migrations.AddField(
            model_name='donorfundmodality',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.organisation'),
        ),
    ]
