# Generated by Django 3.1.13 on 2021-09-20 17:20

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_tables', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.CharField(max_length=35)),
                ('description', models.TextField()),
                ('baseline_year', models.IntegerField()),
                ('baseline_value', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('operating_unit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.operatingunit')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_date', models.DateField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, max_length=600, null=True)),
                ('download_url', models.CharField(blank=True, max_length=600, null=True)),
                ('cron_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_date', models.DateField(auto_now_add=True, null=True)),
                ('cron_type', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('cron_key', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('cron_message', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('contact_email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('contact_website', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('activity_status', models.IntegerField(blank=True, null=True)),
                ('collaboration_type', models.IntegerField(blank=True, null=True)),
                ('default_flow_type', models.IntegerField(blank=True, null=True)),
                ('default_finance_type', models.IntegerField(blank=True, null=True)),
                ('default_aid_type', models.CharField(blank=True, max_length=5, null=True)),
                ('default_tied_status', models.IntegerField(blank=True, null=True)),
                ('capital_spend', models.FloatField(blank=True, null=True)),
                ('conditions_attached', models.IntegerField(blank=True, null=True)),
                ('crs_code', models.CharField(blank=True, max_length=15, null=True)),
                ('operating_unit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.operatingunit')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=30)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=30)),
                ('operating_units', models.IntegerField(default=0)),
                ('projects', models.IntegerField(default=0)),
                ('donors', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SDGMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sdg', models.CharField(max_length=20)),
                ('response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SDGSunburst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdg_year', models.IntegerField()),
                ('response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SectorAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=125)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=30)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=30)),
                ('total_projects', models.IntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=30)),
                ('year', models.IntegerField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.sector')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=30)),
                ('sdg', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.sdgtargets')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('body_text', models.TextField(null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSdg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
                ('sdg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.sdg')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectParticipatingOrganisations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.IntegerField(blank=True, default=None, null=True)),
                ('org_role', models.IntegerField(blank=True, default=None, null=True)),
                ('organisation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('organisation_id', models.CharField(blank=True, max_length=20, null=True)),
                ('org_name', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_url', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('format', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.documentcategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectActivityDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_date', models.DateField(db_index=True)),
                ('activity_type', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectActiveYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_active', to='undp_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='CountryResultPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.CharField(max_length=35)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('actual', models.CharField(blank=True, default=0, max_length=75, null=True)),
                ('target', models.CharField(blank=True, default=0, max_length=75, null=True)),
                ('dimension_name', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('dimension_value', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('country_result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.countryresult')),
                ('operating_unit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.operatingunit')),
            ],
        ),
        migrations.CreateModel(
            name='CountryDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_url', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('format', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.documentcategory')),
                ('operating_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.operatingunit')),
            ],
        ),
        migrations.AddIndex(
            model_name='projectsearch',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='undp_projec_search__2fbdf7_gin'),
        ),
    ]
