# Generated by Django 3.1.13 on 2022-01-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undp_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budgetT',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
