# Generated by Django 3.1.13 on 2022-01-21 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_tables', '0002_auto_20220121_1511'),
        ('undp_projects', '0002_project_budgett'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='executant',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.region'),
        ),
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_tables.sector'),
        ),
    ]
