# Generated by Django 3.1.13 on 2022-01-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undp_projects', '0003_auto_20220121_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='executant',
        ),
    ]
