# Generated by Django 3.1.13 on 2022-01-30 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('undp_projects', '0005_projecttimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='finish_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='ProjectTimeLine',
        ),
    ]
