# Generated by Django 3.1.13 on 2022-02-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undp_projects', '0006_auto_20220130_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='planification_year',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
