# Generated by Django 3.1.13 on 2022-02-06 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undp_projects', '0007_project_planification_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=15, null=True)),
                ('reference_period', models.IntegerField(blank=True, null=True)),
                ('target', models.CharField(blank=True, max_length=15, null=True)),
                ('target_period', models.IntegerField(blank=True, null=True)),
                ('target_status', models.CharField(blank=True, max_length=15, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='undp_projects.project')),
            ],
        ),
    ]
