# Generated by Django 3.1.13 on 2022-02-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undp_projects', '0009_auto_20220211_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beneficiary',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
